# Generated by Django 4.1.6 on 2023-03-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="host",
            field=models.CharField(default="localhost:8000/", max_length=100),
        ),
    ]
