# Generated by Django 4.1.7 on 2023-03-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='users.profile'),
        ),
    ]
