# Generated by Django 4.1.7 on 2023-03-21 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photo')),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(max_length=150)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('howManyLike', models.ManyToManyField(related_name='howManyLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mainlikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainint', models.CharField(default='Like', max_length=5)),
                ('mainPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.post')),
                ('mainUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('main_date', models.DateTimeField(auto_now_add=True)),
                ('main_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comments', to='stream.post')),
            ],
        ),
    ]
