<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-28 22:50

=======
# Generated by Django 4.1.6 on 2023-03-27 20:46

from django.conf import settings
>>>>>>> main
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> main
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Comment',
            fields=[
                ('comment', models.TextField()),
                ('contentType', models.TextField(default='type placeholder')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('contentType', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photo')),
                ('visibility', models.CharField(blank=True, max_length=150, null=True)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('comments', models.ManyToManyField(blank=True, to='stream.comment')),
=======
            name="Post",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/post_photo"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contentType",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("categories", models.CharField(blank=True, max_length=50, null=True)),
                ("count", models.IntegerField(default=0)),
                ("comments", models.CharField(blank=True, max_length=150, null=True)),
                ("visibility", models.CharField(blank=True, max_length=150, null=True)),
                ("unlisted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "howManyLike",
                    models.ManyToManyField(
                        related_name="howManyLike", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mainlikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mainint", models.CharField(default="Like", max_length=5)),
                (
                    "mainPost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stream.post"
                    ),
                ),
                (
                    "mainUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment", models.TextField()),
                ("contentType", models.TextField(default="type placeholder")),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_comments",
                        to="stream.post",
                    ),
                ),
>>>>>>> main
            ],
        ),
    ]
