# Generated by Django 4.1.6 on 2023-03-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="howManyLike",),
    ]
