# Generated by Django 4.1.6 on 2023-03-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0002_remove_post_howmanylike"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="main_post",),
        migrations.RemoveField(model_name="post", name="count",),
        migrations.RemoveField(model_name="post", name="comments",),
        migrations.DeleteModel(name="mainlikes",),
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(blank=True, to="stream.comment"),
        ),
    ]
