# Generated by Django 4.1.6 on 2023-03-24 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0003_post_unlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
