# Generated by Django 4.1.6 on 2023-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_post_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
