# Generated by Django 4.1.6 on 2023-03-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0004_post_published_post_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="test", field=models.TextField(default="tt"),
        ),
    ]
