# Generated by Django 4.1.6 on 2023-03-24 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("stream", "0005_comment_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="test",),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="contentType",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="published",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
